CREATE DATABASE LIBRARY;

CREATE TABLE BOOKS(
BookID INT PRIMARY KEY,
Title VARCHAR(20),
AuthorID INT UNIQUE , 
PublishedYear INT ,
CopiesAvailable INT,
BookCategory VARCHAR(20) );

CREATE TABLE AUTHORS(
AUTHOR_ID INT PRIMARY KEY , 
FIRST_NAME VARCHAR(10),
LAST_NAME VARCHAR(10),
BIRTH_YEAR DATE );

INSERT INTO BOOKS(BookID,Title,AuthorID,PublishedYear,CopiesAvailable,BookCategory)VALUES();
INSERT INTO AUTHORS(AUTHOR_ID,FIRST_NAME,LAST_NAME,BIRTH_YEAR)VALUES();